#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "#3B4252"
bspc config focused_border_color "#88C0D0"
bspc config border_width 0
picom &
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
xsetroot -cursor_name left_ptr &
${HOME}/.fehbg
bspc config focus_follows_pointer true
bspc rule -a discord state=pseudo_tiled rectangle=1200x700+0+0
bspc rule -a feh state=pseudo_tiled
bspc rule -a Thunar state=pseudo_tiled
python3 /home/renan/bin/startpage.py &
/home/renan/.config/polybar/launch2.sh